/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_posts` VALUES
(1,1,"2018-02-19 18:31:06","2018-02-19 18:31:06","Welcome to WordPress. This is your first post. Edit or delete it, then start writing!","Hello world!","","publish","open","open","","hello-world","","","2018-02-19 18:31:06","2018-02-19 18:31:06","",0,"http://rodpress.local/?p=1",0,"post","",1),
(2,1,"2018-02-19 18:31:06","2018-02-19 18:31:06","This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\n\n<blockquote>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</blockquote>\n\n...or something like this:\n\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\n\nAs a new WordPress user, you should go to <a href=\"http://rodpress.local/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!","Sample Page","","publish","closed","open","","sample-page","","","2018-02-19 18:31:06","2018-02-19 18:31:06","",0,"http://rodpress.local/?page_id=2",0,"page","",0),
(3,1,"2018-02-19 18:41:10","0000-00-00 00:00:00","","Auto Draft","","auto-draft","open","open","","","","","2018-02-19 18:41:10","0000-00-00 00:00:00","",0,"http://rodpress.local/?p=3",0,"post","",0),
(4,1,"2018-02-19 18:50:05","2018-02-19 18:50:05","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia sapien orci, id consequat risus tempus at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer tristique massa magna, ac viverra lectus molestie quis. Integer cursus lacus orci, et tincidunt justo convallis nec. Integer volutpat sed urna et lobortis. Duis hendrerit eros vitae nisi hendrerit, in sollicitudin arcu imperdiet. Nullam leo ipsum, pellentesque vitae ornare vitae, vestibulum quis massa. In eu porta leo. Sed ac egestas felis, quis auctor nibh. Praesent nisi tellus, posuere sed nulla et, sodales mollis leo. Suspendisse potenti. Donec mollis scelerisque eleifend. Proin sollicitudin nec tellus aliquet feugiat.\r\n\r\nMorbi sed vehicula est. Mauris urna nisl, scelerisque nec volutpat hendrerit, dignissim eget sapien. Vestibulum dictum risus vehicula magna auctor, eu auctor est fermentum. Aliquam scelerisque sem id semper blandit. Cras lobortis ex lorem, eget vulputate elit rhoncus sed. Mauris mattis ex nec magna lacinia vehicula. Quisque tempor vestibulum diam in placerat.","Lorem Ipsum","","publish","open","open","","lorem-ipsum","","","2018-02-19 18:50:05","2018-02-19 18:50:05","",0,"http://rodpress.local/?p=4",0,"post","",0),
(5,1,"2018-02-19 18:50:05","2018-02-19 18:50:05","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia sapien orci, id consequat risus tempus at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer tristique massa magna, ac viverra lectus molestie quis. Integer cursus lacus orci, et tincidunt justo convallis nec. Integer volutpat sed urna et lobortis. Duis hendrerit eros vitae nisi hendrerit, in sollicitudin arcu imperdiet. Nullam leo ipsum, pellentesque vitae ornare vitae, vestibulum quis massa. In eu porta leo. Sed ac egestas felis, quis auctor nibh. Praesent nisi tellus, posuere sed nulla et, sodales mollis leo. Suspendisse potenti. Donec mollis scelerisque eleifend. Proin sollicitudin nec tellus aliquet feugiat.\r\n\r\nMorbi sed vehicula est. Mauris urna nisl, scelerisque nec volutpat hendrerit, dignissim eget sapien. Vestibulum dictum risus vehicula magna auctor, eu auctor est fermentum. Aliquam scelerisque sem id semper blandit. Cras lobortis ex lorem, eget vulputate elit rhoncus sed. Mauris mattis ex nec magna lacinia vehicula. Quisque tempor vestibulum diam in placerat.","Lorem Ipsum","","inherit","closed","closed","","4-revision-v1","","","2018-02-19 18:50:05","2018-02-19 18:50:05","",4,"http://rodpress.local/4-revision-v1/",0,"revision","",0);
